# SPDX-FileCopyrightText: © 2025 open-nudge <https://github.com/open-nudge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---

ignore: "*README.md"

nav:
  - Why comver?: "why.md"
  - Configuration: "configuration.md"
  - Plugins: "plugins.md"
  - Verification: "verification.md"
...
